name: Export YAML as Env Vars
description: Export all YAML entries as environment variables with double underscore for nesting.
inputs:
  file:
    description: Path to the YAML file
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        export_vars() {
          local prefix=$1
          local file=$2
          for key in $(yq "$prefix | keys | .[]" $file); do
            clean_key=$(echo $key | sed 's/"//g')
            value=$(yq "$prefix.\"$clean_key\"" $file)
            if yq "$prefix.\"$clean_key\"" $file | yq 'tag' | grep -qE '!!map|!!seq'; then
              export_vars "$prefix.\"$clean_key\"" $file
            else
              env_key=$(echo "$prefix.$clean_key" | sed 's/^\.\?//; s/\./__/g; s/-/_/g; s/"//g')
              echo "${env_key}=${value}" >> $GITHUB_ENV
            fi
          done
        }
        export_vars '.' "${{ inputs.file }}"
      shell: bash
