name: 'AWS Authentication'
description: 'Configure AWS credentials and login to ECR'
inputs:
  role-to-assume:
    description: 'AWS Role ARN to assume via OIDC'
    required: true
  role-session-name:
    description: 'Role session name'
    required: false
    default: 'GitHub_to_AWS_via_FederatedOIDC'
  aws-region:
    description: 'AWS Region'
    required: true
outputs:
  registry:
    description: 'ECR Registry URL'
    value: ${{ steps.login-ecr.outputs.registry }}
runs:
  using: 'composite'
  steps:
    - name: 🔑 Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: 🐋 Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
